### ISSUE TITLE
docs: Rest Docs 적용하기

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#131]
## As-is
- API 문서가 노션에 작성되어 있다.

## To-be 
- Rest docs로 api 문서를 관리한다.

### 기대 효과
- 기능 구현 또는 수정시 api 문서가 갱신된다.
- api 명세와 구현이 맞지 않은 문제가 발생될 경우 예외가 발생되어 항상 최신화된 문서를 보장받을 수 있다.

### Todo 
- [ ]  Job1: Rest Docs 환경설정
- [ ]  Job2 : Test에 추가
- [ ]  Job3 : 기존 노션 API 문서를 Rest Docs로 마이그레이션
- [ ] Job4 : CI/CD 파이프라인에 Rest Docs 생성 및 배포 과정 추가
