### ISSUE TITLE
응답 메시지 형식 수정

### ISSUE THREAD

**Issue by big-cir** [Attica-org/athens-backend#146]
## As-is
- response message를 string으로 프론트에게 전달하고 있다. 따라서 json 응답 메시지를 프론트에서 파싱한다.

## To-be 
- reponse message도 json 포맷으로 전달한다.

### 기대 효과
- 프론트에서 따로 파싱하지 않아도 된다.

### Todo 
- [x]  ExceptionHandler 클래스 리팩토링
- [x] ErrorResponse 필드 타입 수정
- [x] 테스트 코드 수정
