### ISSUE TITLE
인기 아고라를 조회한다

### ISSUE THREAD

**Issue by big-cir** [Attica-org/athens-backend#153]
## As-is
- 어떤 아고라가 활발하게 진행되는 아고라인지 알 수 없다.

## To-be 
- 기준을 세우고 여기에 부합하는 아고라 리스트를 응답한다.

### 기대 효과
- 실시간 또는 특정 주기에 따라 활발한 아고라를 사용자가 알 수 있다.

### Todo 
- [x]  어떤 아고리가 활발한 아고라인지 기준을 정한다.
- [x]  인기 아고라 조회 API 추가
- [x] 1시간을 주기로 스케줄링
- [x] 인기 아고리를 관리 도메인/테이블 생성
- [x] 테스트코드 작성

### References (optional)
![agora](https://github.com/user-attachments/assets/fd0f942c-a9eb-4794-a312-86add4e9e9aa)
