### ISSUE TITLE
Jenkins 무중단 배포 설정

### ISSUE THREAD

**Issue by big-cir** [Attica-org/athens-backend#156]
## As-is
- github action으로 cd를 진행하지만 재배포시 애플리케이션이 종료되는 텀이 생긴다.

## To-be 
- cd 환경을 jenkins로 변경하고 무중단 배포로 변경한다.

### 기대 효과
- jenkins를 사용해서 다른 repo에서 깃액션 Key를 사용하지 않아도 됨

### Todo 
- [ ]  cd jenkins로 변경
- [ ]  blue/green 무중단 배포
- [ ] Healcheck 컨트롤러 설정
