### ISSUE TITLE
아고라 수정 API 추가 및 생성 API 리팩토링

### ISSUE THREAD

**Issue by big-cir** [Attica-org/athens-backend#169]
## As-is
- 아고라를 생성할 때 프로필 이미지를 설정할 수 없다.
- 생성된 아고라의 프로필 이미지를 변경할 수 없다.

## To-be 
- 사용자가 아고라를 생성할 때 프로필 이미지를 설정할 수 있다.
- 생성된 아고라의 프로필 이미지를 변경할 수 있다.

### Todo 
- [x]  아고라 생성 API 리팩토링
- [x]  아고라 프로필 이미지 수정 API 추가
- [x] 아고라 생성 member 식별자 추가
