### ISSUE TITLE
프론트엔드 요구사항 반영 및 리팩토링

### ISSUE THREAD

**Issue by yybmion** [Attica-org/athens-backend#190]
## As-is
- 프론트엔드 요구사항에 따라 수정 및 리팩토링을 진행한다.

### Todo 
- [ ]  Job1: 채팅 나가기 api의 Request Header의 agoraId 제거(CORS 에러) 
- [ ]  Job2: 아고라 id로 아고라 정보 불러오는 api 응답에 imgUrl도 추가
- [ ]  Job3: 종료된 아고라 빈 배열로 응답
- [ ]  Job4: 아고라 수정에서 성공 응답에 저장한 이미지에 대한 path 전달 추가
- [ ]  Job5: **아고라 입장하기 - 입장한 사용자가 아고라를 생성한 사용자인지 알려주는 응답 필요**
- [ ]  Job6: 아고라 조회시 찬/반 인원 일치하지 않는데 꽉 찼다고 뜨는 경우
- [ ]  Job7: 아고라 조회시 아무도 없는 아고라에 인원 그대로 남아있음
- [ ]  Job8: 카카오 로그인 kakao 측에서 canceled 시키는 것
- [ ]  Job9: 토큰 재발급 api 타입 불일치 1002 에러
- [ ]  Job10: 관찰자가 반응을 보낼 때, '채팅 전송하기'의 에러 중 하나인 '관찰자가 채팅을 보낼 경우' 가 반환
- [ ]  Job11: 테스트코드 수정
