### ISSUE TITLE
WebSocket을 이용한 채팅 서버 구현

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#21]
## As-is
- 채팅 도메인의 API를 제공하지 않는다.

## To-be 
- 채팅 도메인의 API를 제공한다.

### Todo 
- [x]  채팅 entity 생성
- [x] http : 채팅 내역 조회하기 API
- [x] http : 채팅 유저 조회하기 API
- [x] websocket : 채팅 전송하기 API
- [x] websocket: 채팅 실시간 메타정보 조회하기 API

### comment
- 처음에는 간단하게 `websocket+stomp`으로 개발하여 구현하기
- `redis` 사용 고려하기 -> 모든 채팅이 저장되어야할까?
- 채팅 데이터 저장 `rdb` vs `nosql` 고려하기
- `webflux`를 이용한 비동기 처리 ---> 기술적 난이도 O

### References (optional)
- [spring 리액티브 websocket 번역본 (토리맘)](https://godekdls.github.io/Reactive%20Spring/websockets//)
- [배민쇼핑라이브를 만드는 기술: 채팅 편](https://techblog.woowahan.com/5268/)
