### ISSUE TITLE
아고라 유저 추방 투표 API 추가

### ISSUE THREAD

**Issue by big-cir** [Attica-org/athens-backend#233]
## As-is
- 토론 주제에 맞지 않는 채팅 혹은 악인을 추방할 수 없다.

## To-be 
- 유저 간 추방 투표 기능 추가

### 기대 효과
- 토론하기 원활한 채팅방 구성

### Todo 
- [ ]  추방 투표 API 추가
- [ ]  중복 투표 사용자 검증
- [ ]  퇴장 메시지 전송
- [ ] previous job: 인기 아고라가 존재하지 않을 경우 null 반환 수정
