### ISSUE TITLE
회원 탈퇴 기능 개발

### ISSUE THREAD

**Issue by yybmion** [Attica-org/athens-backend#239]
## As-is
- 회원 탈퇴에 대한 기능이 필요함.

## To-be 
- 회원이 안전하게 탈퇴처리 된다.
- `Soft delete`? `Hard delete`?
- 복구 가능성을 염두하여 **데이터베이스에서 즉시 삭제하지 않음**.
- 탈퇴한 시간을 업데이트하여 이후 `스케쥴러`를 통해 매월 검사를 한다.
- 탈퇴한 회원이 탈퇴한지 **6개월 이상 되었다면 영구적으로 삭제**한다.

### 기대 효과
- 위와 같은 방식으로 구현하면 안전하게 오래된 데이터를 정리하면서도, 필요한 정보는 보존할 수 있다.

### Todo 
- [ ]  Job1: 회원 탈퇴 요청 시 soft delete
- [ ]  Job2: 스케쥴러를 통해 회원 탈퇴 확인
- [ ]  Job3: 특정 기간이 지나면 영구적인 회원 삭제
- [ ]  Job4: 복구 메서드 또한 추가
