### ISSUE TITLE
ERD 기반 Entity 생성 및 리팩토링

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#30]
# As-is
- 작성한 erd에 따라 엔티티 간 연관관계가 설정되어 있지 않다.
- 구현되어 있지 않은 도메인이 존재한다.

## To-be 
- ERD를 기반으로 엔티티 클래스를 생성하고 연관 관계를 설정한다.
- 리팩토링을 수행한다.

### 기대 효과
- 변경 또는 기능 개발이 가져올 긍정적인 효과 기술 (기능 향상, 사용자 경험 개선, 처리 속도 증가, 유지 보수 용이성)

### Todo 
- [x] ERD를 기반으로 각 엔티티 간의 연관 관계를 설정한다.
- [x] 엔티티 클래스의 필드 이름과 타입이 ERD와 일치하도록 수정한다.
- [x] 정적 팩토리 메소드를 추가한다.
- [x] 엔티티 클래스 내부의 필드, 생성자, 메소드 순서를 일관되게 정리한다.
