### ISSUE TITLE
Agora keyword & category 기반 검색 API 구현

### ISSUE THREAD

**Issue by big-cir** [Attica-org/athens-backend#32]
## As-is
- 아고라를 조회하는 API가 없다.

## To-be 
- 검색 기능과 API를 추가한다.
- cursor based pagination으로 제공한다.

### Todo 
- [ ]  아고라 키워드를 기반으로 조회 기능 및 API 추가
- [ ]  아고라 카테고리를 기반으로 조회 기능 및 API 추가
- [ ]  작업한 내용 중 수정, 보완이 필요한 부분들을 확인 후, 리팩토링
