### ISSUE TITLE
feat: Spring Security를 활용한 비회원 로그인 구현

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#4]
## As-is
- 사용자 인증 및 로그인 기능이 없다.

## To-be 
- `Spring Security`를 활용하여 비회원 로그인 기능을 구현한다.
- 추후 회원 로그인 기능을 추가할 수 있도록 확장성 있게 설계한다.

### 기대 효과
- 비회원 로그인을 지원함으로써 사용자 접근성이 높아진다.
- 회원 로그인 기능을 도입하는 것을 고려하여 확장 가능한 아키텍처를 설계한다.

### Todo 
- [x]  Spring Security 기본 설정
- [x]  비회원 사용자를 대상으로 한 임시 jwt 토큰 발급 및 검증 로직 구현
- [x] 인증 필터 구현
- [x] 비회원 사용자 정보를 저장하는 Domain, Repository, Controller 설계 및 구현
- [x] 테스트 코드 작성 및 검증 @yybmion 

### References (optional)
- [Spring Security 공식 문서](https://docs.spring.io/spring-security/reference/index.html)
- [비회원 로그인 질문](https://www.inflearn.com/questions/118904/%EB%B9%84%ED%9A%8C%EC%9B%90-%EC%9B%B9%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%B3%B4%EC%95%88)
