### ISSUE TITLE
토론 API 구현

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#54]
## As-is
- 채팅이 시작하거나 종료할 때 아고라의 상태가 바뀌지 않는다.
- 프론트 요구사항이 변경됨에 따라 응답 데이터의 수정이 필요하다.
- 에러 코드와 상관없이 예외만 던진다.

## To-be 
- 채팅이 시작하거나 종료할 때 아고라의 상태가 바뀐다.
- 프론트 요구사항에 맞는 응답 데이터를 제공한다.
- 정의했던 커스텀 예외로 예외처리를 수행한다.

### 기대 효과
- 일관성, 정합성
- 비즈니스 검증 로직 

### Todo 
- [x]  토론 시작하기 API
- [x]  토론 종료하기 API
- [x]  토론 메타정보 조회하기 API - 토론 시작시간 추가하기
- [x]  에러 캐치

### 참고
아고라(공간) + 채팅(행위) = 토론
