### ISSUE TITLE
토론 시작/종료 알림 기능 구현

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#59]
## As-is
- **채팅이 시작되거나 종료되었을 때 클라이언트에서 요청을 보내지 않으면 실시간으로 토론 상태를 알 수 없다.**

## To-be 
-  **채팅이 시작되거나 종료될 경우 모든 토론 참여자에게 실시간으로 알림을 보낸다.**

### 기대 효과
- 비즈니스 검증 로직 

### Todo 
- [x] 알림 구현 기술 선택 : 웹소켓 vs SSE => [Discussion 근거 정리](https://github.com/Attica-org/athens-backend/discussions/80)
- [x] 토론 시작 알림 기능 구현
- [x] 토론 종료 알림 기능 구현

**Comment by Starlight258** [comment]
웹소켓 vs SSE : 웹소켓 선택
[Discussion 근거 정리](https://github.com/Attica-org/athens-backend/discussions/80)
