### ISSUE TITLE
웹소켓 예외 처리

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#60]
## As-is
- 웹소켓에서 예외가 발생할 경우 500에러가 뜨고 에러 메세지가 전달되지 않는다.
- 클라이언트는 어떤 부분에서 예외가 발생했는지 모른다.

## To-be 
- 웹소켓에서 예외가 발생할 경우 적절한 예외 메세지로 응답한다.
- 적절히 로그를 남긴다.

### 기대 효과
- 디버깅 편리, 예외 처리

### Todo 
- [x]  웹소켓 예외 처리 방법 알아보기
- [x] 에러 코드 정의하기
- [x] 예외 처리 구현하기
- [x] API 문서에 정리하기

### References (optional)
- [웹소켓 코딩시 꼭 알아야 할 에러 처리 전략](https://mytory.net/archives/14526/)
- [Spring docs : websocket / event](https://docs.spring.io/spring-framework/reference/web/websocket/stomp/application-context-events.html)
