### ISSUE TITLE
투표 및 투표 결과 반환 기능 구현

### ISSUE THREAD

**Issue by yybmion** [Attica-org/athens-backend#64]
## As-is
- Agora가 종료상태가 되면 투표를 진행한다. 
- 투표는 반대 또는 찬성을 선택할 수 있다.
- 15초 동안 투표를 진행한 이후 결과를 반환한다.

## To-be 
- 15초 동안 투표를 진행하고 찬성 :00명 반대 :00명을 반환
- 투표 반환 수가 과반수가 넘은 쪽이 토론 승리

### 고려할 점
- 클라이언트 네트워크 환경에 따라 반환받는 투표 결과가 달라질 수 있음

### Todo 
- [x]  Job1: 투표 api
- [x]  Job2: 투표 결과 반환 api
- [x]  Job3: Scheduler를 사용한 투표 시간 조절
