### ISSUE TITLE
feat: CI/CD pipeline with Actions

### ISSUE THREAD

**Issue by big-cir** [Attica-org/athens-backend#9]
## As-is
- Springboot 애플리케이션에서 CI/CD 워크플로우 필요.

## To-be 
- CI/CD 스크립트 추가
- PR 생성 시 빌드 수행 및 자동화된 프로세스 구성

### 기대 효과
- 개발 속도 향상 및 오버헤드 비용 절감

### Todo 
- [x]  checkstyle로 코드 퀄리티 유지
- [x]  CI 스크립트 추가
- [ ]  배포 자동화 스크립트 추가
