### ISSUE TITLE
AgoraUser 세션 관리와 Agora 종료

### ISSUE THREAD

**Issue by yybmion** [Attica-org/athens-backend#90]
## As-is
- 현재 Agora를 start한 이후에 사용자가 방에 없어도 agora의 상태가 유지되었다.

## To-be 
- Agora를 start 한 이후 사용자가 방에 아무도 없다면 상태를 `CLOSED` 상태로 변경한다.
- AgoraUser에 `SessionId`와 `isDeleted` 필드를 추가하여 아고라에 있는 세션이 연결된 사용자가 있는지 확인한다.
- 세션이 끊겼다면(EventListener) `isDeleted` boolean 타입 필드를 true로 만든다.
- 특정 Agora의 AgoraUser 모두가 `isDeleted` 필드가 true가 되었다면 현재 방에 사용자들의 세션이 모두 종료되었다는 의미이므로 
- 종료 api를 요청하여 `Agora Status`를 `CLOSED` 상태로 변경한다.

### 기대 효과
- Session 연결에 관한 Agora Status도 관리한다.

### Todo 
- [x]  Job1: AgoraUser에 `SessionId` 추가
=> AgoraUser는 아고라에 참여한 유저를 의미하며 Agora와 User 모두 연관된 정보이다. 
- [x]  Job2: 세션 연결시 `sessionId`를 `현재 세션 id`로 업데이트, 연결 종료시 `sessionId=null` 로 설정
- [x]  Job3: 모든 세션이 끊기면 종료 api를 요청하여 `Agora Status`를 `CLOSED` 상태로 변경

### Discussion
[세션 관련 제안](https://github.com/Attica-org/athens-backend/discussions/94)
